version: '3'
services:
  db:
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - ~/.docker-conf/shift/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - test_network
  app_api:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: "./bin/rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - .:/rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - test_network

volumes:
  postgres_data: {}
  app_storage: {}

networks:
  test_network:
    driver: bridge
