---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/shifts":
    get:
      summary: List shifts eligibility
      tags:
      - Shifts
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per
        in: query
        required: false
        description: Number of items per page
        schema:
          type: integer
      - name: profession
        in: query
        required: false
        description: Number of items per page
        schema:
          type: integer
      - name: facility_id
        in: query
        required: true
        description: Facility ID
        schema:
          type: integer
      - name: start_date
        in: query
        required: true
        description: Start date
        schema:
          type: string
      - name: end_date
        in: query
        required: true
        description: End date
        schema:
          type: string
      - name: profession
        in: query
        type: string
        required: false
        description: Profession type
        schema:
          type: string
          enum:
          - CNA
          - LVN
          - RN
          example: RN
      responses:
        '200':
          description: shifts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  shifts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/shift"
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                        x-nullable: true
                      prev_page:
                        type: integer
                        x-nullable: true
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
        '422':
          description: unprocessable entity
        '404':
          description: facility not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    shift:
      properties:
        id:
          type: integer
        start:
          type: string
        end:
          type: string
        is_deleted:
          type: boolean
        profession:
          type: string
        facility_id:
          type: integer
        facility:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            is_active:
              type: boolean
